engines:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
    channel: "beta"

ratings:
  paths:
  - "**.java"

exclude_paths:
- "**.png"
- "**.ttf"
- "**.ico"
- "**.js"
